
language: python
sudo: required
# https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against
python:
  - "3.6.1"
services:
  - docker

env:
  -
  - NGROK_TOKEN=2udLnkVZezfMaxiVLMPNH_2n7ZZGYKVD27scQA7eQXs

before_install:
  # update docker
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  # ngrok hack
  - eval "$(curl -sL https://raw.github.com/fniephaus/travis-remote-shell/master/run.sh)"

install:
  # note: this will also upgrade docker compose
  - pip install --upgrade -r requirements.txt

# before_script:
#   - sleep 1

script:
  - docker -v
  - docker-compose -v
  - pip freeze | grep rapydo-
  - rapydo --version
  # REMOVE ME
  - sleep 999999

  # Clone subrepos
  - rapydo init

  # needed to let the system create files with test coverage
  - chmod o+w backend

  # build docker images
  - rapydo build

  # start the debug environment, and wait for initialization
  - rapydo control start && sleep 10

  # LOGS
  # - rapydo --services postgres log
  # - rapydo --services backend log

  # launch all unittests
  - rapydo --services backend shell --command "/bin/bash -c 'testwithcoverage'"

  # # if client shell needed
  # rapydo --services restclient shell --user developer

after_success:
  - coveralls
